.PHONY:all

all:sender catcher sender2 catcher2 sender3 catcher3

sender:sender.c
	gcc -Wall -o $@ $^
catcher:catcher.c
	gcc -Wall -o $@ $^
sender2:sender2.c
	gcc -Wall -o $@ $^
catcher2:catcher2.c
	gcc -Wall -o $@ $^
sender3:sender3.c
	gcc -Wall -o $@ $^
catcher3:catcher3.c
	gcc -Wall -o $@ $^